---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helloenv-app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  url: ssh://git@github.com/sudhanshu456/helloenv-app
